version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies ...."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Running unit tests to test the lambda function logic ...."
      - python -m pytest tests/
      - echo "Done running unit tests!"
      - echo "Creating deployment_package.zip ...."
      - mkdir lib
      - cp -R *.py lib
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      - echo "Done creating the deployment_package.zip!"
  post_build:
    commands:
      - echo "Updating lambda function import-waze-s3 ...."
      - aws lambda update-function-code --function-name import-waze-s3 --zip-file fileb://deployment_package.zip
      - echo "Done updating the lambda function import-waze-s3!"